alias ..='cd ..'
alias studiumcd='cd ~/Documents/sf/documents/studium/sem1'
alias i3cfg='vim ~/.config/i3/config'
alias nltwitch='streamlink twitch.tv/northernlion best'
alias krita='./.krita.appimage'
alias ledger='vim ~/.notes/ledger.txt'
alias texplate='cp ~/.texplate.tex temp.tex && printf "rename by typing: mv temp.tex newfilename.tex\n" && printf "remove by typing: rm temp.tex\n"'
alias lolight='xbacklight -set 1'
alias hilight='xbacklight -set 100'
alias dotfilecollect='cp ~/.vimrc ~/gits/dotfiles && cp ~/.config/i3/config ~/gits/dotfiles && cp ~/.bashrc ~/gits/dotfiles && cp ~/.Xresources ~/gits/dotfiles && cp ~/.bash_aliases ~/gits/dotfiles && cd ~/gits/dotfiles && git status'
alias chatty='thunar ~/.chatty/Chatty.jar'
alias showclock='tty-clock -cC 7'
alias lowlight='xbacklight -set 1'
alias fullight='xbacklight -set 100'
alias weatherrep='curl -s wttr.in/Bremen'

