stylesheet:

categories:
  - name: work::notrack
    color: '#dfbcbc'
  - name: work
    color: '#ffcccc'
    priority: 20
  - name: uni
    color: '#eedccc'
    priority: 10
  - name: uni::pmwk
    color: '#eeaccc'
    priority: 10
  - name: uni::namib
    color: '#ffdccc'
    priority: 15
  - name: fitness
    color: '#ccebff'
  - name: hygiene
    color: '#efafff'
  - name: leisure
    color: '#ffccf7'
  - name: gardening
    color: '#c8e1ab'
  - name: eating
    color: '#c2edab'
  - name: cooking
    color: '#ccffe6'
  - name: learning
    color: '#ccf0cc'
  - name: programming
    color: '#fff0cc'
  - name: reading
    color: '#f3ffcc'
  - name: 'security/pentesting practice'
    color: '#aacae3'
  - name: household
    color: '#cccccc'
  - name: important
    color: '#cc9999'
  - name: default
    color: '#cecece'
  - name: wasted
    color: '#eeeeee'
