stylesheet:

categories:
  - name: work::notrack
    fg: '#800000'
    bg: '#ffcccc'
  - name: work
    fg: '#000000'
    bg: '#ffcccc'
    priority: 20
  - name: uni
    fg: '#000000'
    bg: '#eedccc'
    priority: 10
  - name: uni::pmwk
    fg: '#000000'
    bg: '#eeaccc'
    priority: 10
  - name: uni::namib
    fg: '#000000'
    bg: '#ffdccc'
    priority: 15
  - name: fitness
    fg: '#000000'
    bg: '#ccebff'
  - name: hygiene
    fg: '#000000'
    bg: '#efafff'
  - name: leisure
    fg: '#000000'
    bg: '#ffccf7'
  - name: gardening
    fg: '#000000'
    bg: '#c8e1ab'
  - name: eating
    fg: '#000000'
    bg: '#c2edab'
  - name: cooking
    fg: '#000000'
    bg: '#ccffe6'
  - name: learning
    fg: '#000000'
    bg: '#ccf0cc'
  - name: programming
    fg: '#000000'
    bg: '#fff0cc'
  - name: reading
    fg: '#000000'
    bg: '#f3ffcc'
  - name: 'security/pentesting practice'
    fg: '#000000'
    bg: '#aacae3'
  - name: household
    fg: '#000000'
    bg: '#cccccc'
  - name: important
    fg: '#000000'
    bg: '#cc9999'
  - name: default
    fg: '#888888'
    bg: '#cecece'
  - name: wasted
    fg: '#a30000'
    bg: '#eeeeee'
