[theme.overrides]

idle_fg = "#aaaaaa"
idle_bg = "#ffffff"

info_fg = "#000000"
info_bg = "#ffffff"

warning_fg = "#000000"
warning_bg = "#fff0cc"

critical_fg = "#000000"
critical_bg = "#ffcccc"

good_fg = "#000000"
good_bg = "#c2edab"

separator = ""

[icons]
name = "awesome5"


[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = true
on_click = "/home/ztf/scripts/micmutetoggle.sh"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"


[[block]]
block = "custom"
command = "echo Worked: $(.scripts/convertsecs.sh $(cat /home/ztf/.worktime/$(date +%Y-%m-%d).timelog))"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
format = "{icon} {available}"
unit = "GB"
interval = 20
warning =  2.0
alert =  1.0

[[block]]
block = "memory"
format_mem = "{mem_avail_percents} avail."
display_type = "memory"

[[block]]
block = "cpu"
interval = 0.25
format = "{barchart} ({frequency})"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}C (CPU)"
chip = "k10temp-pci-00c3"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}C (GPU)"
chip = "amdgpu-pci-0900"

[[block]]
block = "networkmanager"
primary_only = true
ap_format = "{strength}"
device_format = "{icon}"
#               "{icon}{ap} {ips}"
on_click = ""

[[block]]
block = "battery"
format = "{percentage} {time}"
interval = 10
device = "BAT1"

[[block]]
block = "weather"
format = "{weather} {temp}C, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "<api key>", city_id = "2856500", units = "metric" }
interval = 600

[[block]]
block = "time"
interval = 1
format = "%a %d.%m. %R"
