[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#000000"
separator = ""

[icons]
name = "awesome"


[[block]]
block = "custom"
command = "/home/ztf/.scripts/is_muted.sh"
json = true
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = true
on_click = "/home/ztf/.scripts/micmutetoggle.sh"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"


[[block]]
block = "custom"
command = "echo Worked: $(.scripts/convertsecs.sh $(cat /home/ztf/.worktime/$(date +%Y-%m-%d).timelog))"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 0.25
format = "{barchart} ({frequency}GHz)"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C (CPU)"
chip = "k10temp-pci-00c3"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C (GPU)"
chip = "amdgpu-pci-0900"

[[block]]
block = "networkmanager"
primary_only = true
ap_format = "{strength}"
device_format = "{icon} {typename}"
#               "{icon}{ap} {ips}"
on_click = ""

[[block]]
block = "weather"
format = "{weather} {temp}°C, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "<api key>", city_id = "2856500", units = "metric" }
interval = 600

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
