[theme.overrides]

idle_fg = "#aaaaaa"
idle_bg = "#ffffff"

info_fg = "#000000"
info_bg = "#ffffff"

warning_fg = "#000000"
warning_bg = "#fff0cc"

critical_fg = "#000000"
critical_bg = "#ffcccc"

good_fg = "#000000"
good_bg = "#c2edab"

separator = ""

[icons]
icons = "awesome5"
[icons.overrides]
sun = ""
moon = ""

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "/home/ztf/scripts/micmutetoggle.sh"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon $available"
alert_unit = "GB"
interval = 20
warning =  2.0
alert =  1.0

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_total_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 0.25
format = " $icon $barchart ($frequency ($utilization)) "

[[block]]
block = "temperature"
interval = 10
format = " $icon[cpu:$average] "
chip = "k10temp-pci-00c3"

[[block]]
block = "temperature"
interval = 10
format = " $icon[gpu:$average] "
chip = "amdgpu-pci-0900"

[[block]]
block = "net"
format = "  $icon[ ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)] "
format_alt = "  $icon[ ^icon_net_down $graph_down$speed_down.eng(prefix:K) ^icon_net_up $graph_up$speed_up.eng(prefix:K)] "

[[block]]
block = "battery"
format = " $percentage $time "
interval = 10
device = "BAT1"

[[block]]
block = "backlight"
format = " $icon "
invert_icons = true
missing_format = ""

[[block]]
block = "custom"
command = "/home/ztf/scripts/,theme-util i3status-rust-block | jq -c"
interval = 120
json = true
format = " $icon "
[[block.click]]
button = "left"
update = true
sync = true
cmd = "/home/ztf/scripts/,theme-util switch"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S', l:en_US) "
