[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#000000"

[icons]
name = "none"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C (CPU)"
chip = "k10temp-pci-00c3"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C (GPU)"
chip = "amdgpu-pci-0300"

[[block]]
block = "networkmanager"
primary_only = true
ap_format = "{strength}"
device_format = "{icon} {typename}"
#               "{icon}{ap} {ips}"
on_click = ""

[[block]]
block = "sound"

[[block]]
block = "weather"
format = "{weather} {temp}°C, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "<api key>", city_id = "2856500", units = "metric" }
interval = 600

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
