local colors = {
-- PATCH_OPEN
Normal = {fg = "#000000", bg = "#FFFFFF"},
NormalNC = {link = "Normal"},
Bold = {bold = true},
Comment = {fg = "#B3B3B3"},
Conceal = {fg = "#A30000"},
Constant = {fg = "#42861D", underline = true},
["@constant"] = {link = "Constant"},
Cursor = {},
CursorIM = {},
CursorLine = {bg = "#F7F7F7"},
ColorColumn = {link = "CursorLine"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#B3B3B3", bold = true},
DarkBlueBackground = {bg = "#0065A3"},
DarkBlueBlock = {fg = "#0065A3", bg = "#0065A3"},
DarkBlueText = {fg = "#0065A3"},
DarkGreenBackground = {bg = "#42861D"},
DarkGreenBlock = {fg = "#42861D", bg = "#42861D"},
DarkGreenText = {fg = "#42861D"},
DarkPinkBackground = {bg = "#A3008B"},
DarkPinkBlock = {fg = "#A3008B", bg = "#A3008B"},
DarkPinkText = {fg = "#A3008B"},
DarkRedBackground = {bg = "#A30000"},
DarkRedBlock = {fg = "#A30000", bg = "#A30000"},
DarkRedText = {fg = "#A30000"},
DarkTurquoiseBackground = {bg = "#00A354"},
DarkTurquoiseBlock = {fg = "#00A354", bg = "#00A354"},
DarkTurquoiseText = {fg = "#00A354"},
DarkYellowBackground = {bg = "#CC8F00"},
DarkYellowBlock = {fg = "#CC8F00", bg = "#CC8F00"},
DarkYellowText = {fg = "#CC8F00"},
Delimiter = {fg = "#B3B3B3"},
["@punctuation.delimiter"] = {link = "Delimiter"},
["@puncuation.special"] = {link = "Delimiter"},
DiagnosticError = {fg = "#FF1414"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticFloatingWarn = {fg = "#A37200"},
DiagnosticHint = {fg = "#F500D0"},
DiagnosticInfo = {fg = "#14A5FF"},
DiagnosticSignError = {fg = "#A30000", bg = "#FFD1D1"},
DiagnosticSignWarn = {fg = "#A37200", bg = "#FFF1D1"},
DiagnosticWarn = {fg = "#FFB914"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#E1F6D5"},
NvimTreeFileStaged = {link = "DiffAdd"},
diffAdded = {link = "DiffAdd"},
DiffChange = {bg = "#FFF0CC"},
NvimTreeFileDirty = {link = "DiffChange"},
diffChanged = {link = "DiffChange"},
DiffDelete = {bg = "#FFCCCC"},
NvimTreeFileNew = {link = "DiffDelete"},
WildMenu = {link = "DiffDelete"},
diffRemoved = {link = "DiffDelete"},
DiffText = {bg = "#FF8A8A"},
NvimTreeFileMerge = {link = "DiffText"},
Directory = {},
EndOfBuffer = {},
Error = {fg = "#A30000", bg = "#FFCCCC"},
ErrorMsg = {link = "Error"},
Floaterm = {bg = "#E6E6E6"},
FoldColumn = {fg = "#0065A3", bold = true},
Folded = {fg = "#0065A3", bg = "#FAFDFF", bold = true, italic = true},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {bg = "#EDF9E6"},
GitSignsAddFG = {fg = "#42861D"},
GitSignsAddLnInline = {fg = "#274F11"},
GitSignsChange = {bg = "#FFF6E0"},
GitSignsChangeFG = {fg = "#CC8F00"},
GitSignsChangeLnInline = {fg = "#7A5600"},
GitSignsDelete = {bg = "#FFE0E0"},
GitSignsDeleteFG = {fg = "#A30000"},
GitSignsDeleteLnInline = {fg = "#610000"},
GocCovered = {bg = "#E1F6D5"},
GocNormal = {bg = "#E6E6E6"},
GocUncovered = {bg = "#FFCCCC"},
Identifier = {bold = true},
Function = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {bg = "#FF70EA"},
Italic = {italic = true},
Keyword = {fg = "#000000", italic = true},
Conditional = {link = "Keyword"},
Exception = {link = "Keyword"},
Label = {link = "Keyword"},
Repeat = {link = "Keyword"},
["@keyword"] = {link = "Keyword"},
LineNr = {fg = "#CCCCCC"},
MatchParen = {fg = "#242424", bg = "#CCFFE6"},
ModeMsg = {fg = "#CCCCCC"},
MoreMsg = {},
MsgArea = {},
MsgSeparator = {},
NeogitStagedchanges = {fg = "#42861D", bold = true, underline = true},
NeogitStashes = {fg = "#0065A3", bold = true, underline = true},
NeogitUnstagedchanges = {fg = "#CC8F00", bold = true, underline = true},
NeogitUntrackedfiles = {fg = "#A30000", bold = true, underline = true},
NormalFloat = {fg = "#000000", bg = "#E6E6E6"},
FloatermBorder = {link = "NormalFloat"},
WhichKeyFloating = {link = "NormalFloat"},
Float = {link = "Number"},
NvimTreeCursorLine = {bg = "#E6E6E6"},
NvimTreeFileDeleted = {link = "NvimTreeFileDirty"},
NvimTreeFileRenamed = {link = "NvimTreeFileDirty"},
NvimTreeFolderIcon = {},
NvimTreeFolderName = {fg = "#14A5FF", bold = true},
NvimTreeEmptyFolderName = {link = "NvimTreeFolderName"},
NvimTreeOpenedFolderName = {link = "NvimTreeFolderName"},
NvimTreeGitIgnored = {fg = "#B3B3B3"},
NvimTreeImageFile = {},
NvimTreeMarkdownFile = {},
NvimTreeNormal = {bg = "#F7F7F7"},
NvimTreeOpenedFile = {},
NvimTreeRootFolder = {},
NvimTreeSpecialFile = {},
Operator = {fg = "#0065A3"},
PaleBlueBackground = {bg = "#CCEBFF"},
PaleBlueBlock = {fg = "#CCEBFF", bg = "#CCEBFF"},
PaleBlueText = {fg = "#CCEBFF"},
PaleGreenBackground = {bg = "#E1F6D5"},
PaleGreenBlock = {fg = "#E1F6D5", bg = "#E1F6D5"},
PaleGreenText = {fg = "#E1F6D5"},
PalePinkBackground = {bg = "#FFCCF7"},
PalePinkBlock = {fg = "#FFCCF7", bg = "#FFCCF7"},
PalePinkText = {fg = "#FFCCF7"},
PaleRedBackground = {bg = "#FFCCCC"},
PaleRedBlock = {fg = "#FFCCCC", bg = "#FFCCCC"},
PaleRedText = {fg = "#FFCCCC"},
PaleTurquoiseBackground = {bg = "#CCFFE6"},
PaleTurquoiseBlock = {fg = "#CCFFE6", bg = "#CCFFE6"},
PaleTurquoiseText = {fg = "#CCFFE6"},
PaleYellowBackground = {bg = "#FFF0CC"},
PaleYellowBlock = {fg = "#FFF0CC", bg = "#FFF0CC"},
PaleYellowText = {fg = "#FFF0CC"},
Pmenu = {fg = "#999999", bg = "#E6E6E6"},
PmenuSbar = {bg = "#E6E6E6"},
PmenuSel = {fg = "#5C5C5C", bg = "#E0E0E0", bold = true},
ColortilsCurrentLine = {link = "PmenuSel"},
PmenuThumb = {bg = "#B8B8B8"},
PreProc = {italic = true},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Question = {},
QuickFixLine = {},
ScrollView = {bg = "#CCEBFF"},
Search = {bg = "#FFCCF7"},
SignColumn = {},
SignifySignAdd = {fg = "#42861D", bg = "#E1F6D5"},
SignifySignChange = {fg = "#CC8F00", bg = "#FFF0CC"},
SignifySignChangeDelete = {link = "SignifySignChange"},
SignifySignDelete = {fg = "#A30000", bg = "#FFCCCC"},
SignifySignDeleteFirstLine = {link = "SignifySignDelete"},
Special = {fg = "#487133"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
SpecialComment = {fg = "#7D7D7D"},
SpecialKey = {fg = "#A30000"},
SpellBad = {bg = "#FFCCCC"},
SpellCap = {bg = "#FFF0CC"},
SpellLocal = {bg = "#E1F6D5"},
SpellRare = {bg = "#CCEBFF"},
Statement = {fg = "#000000", bold = true, italic = true},
StatusLine = {fg = "#8F8F8F", bg = "#E6E6E6", bold = true},
NvimTreeStatusLine = {link = "StatusLine"},
TablineSel = {link = "StatusLine"},
StatusLineNC = {fg = "#B3B3B3", bg = "#F7F7F7"},
NvimTreeStatusLineNC = {link = "StatusLineNC"},
Tabline = {link = "StatusLineNC"},
String = {fg = "#42861D"},
Boolean = {link = "String"},
Character = {link = "String"},
Number = {link = "String"},
["@string"] = {link = "String"},
Structure = {italic = true},
Substitute = {},
TelescopeBorder = {fg = "#FFF0CC", bg = "#FFF0CC"},
TelescopeMatching = {fg = "#8A6000", bg = "#FFD675", bold = true},
TelescopeNormal = {fg = "#000000", bg = "#FFF0CC"},
TelescopeNormalBorder = {link = "TelescopeNormal"},
TelescopePreviewMessage = {fg = "#949494"},
TelescopePreviewNormal = {fg = "#000000", bg = "#F7F7F7"},
TelescopePreviewBorder = {link = "TelescopePreviewNormal"},
TelescopePreviewTitle = {fg = "#4A4A4A", bg = "#C7C7C7", italic = true},
TelescopePromptBorder = {fg = "#E1F6D5", bg = "#E1F6D5"},
TelescopePromptCounter = {fg = "#387119"},
TelescopePromptNormal = {fg = "#000000", bg = "#E1F6D5"},
TelescopePromptPrefix = {fg = "#387119", bold = true},
TelescopePromptTitle = {fg = "#387119", bg = "#AAE58A", italic = true},
TelescopeSelection = {fg = "#000000", bg = "#FFE29E"},
TelescopeSelectionCaret = {fg = "#A37200", bg = "#FFE29E", bold = true},
TelescopeTitle = {fg = "#8A6000", bg = "#FFD470", italic = true},
TermCursor = {fg = "#FFFFFF", bg = "#000000"},
TermCursorNC = {bg = "#666666"},
Title = {fg = "#A30000", bold = true},
manOptionDesc = {link = "Title"},
Todo = {bg = "#FFCCCC"},
Type = {underline = true},
StorageClass = {link = "Type"},
Typedef = {link = "Type"},
["@type"] = {link = "Type"},
URI = {fg = "#0065A3"},
Underlined = {underline = true},
VertSplit = {fg = "#F7F7F7", bg = "#F7F7F7"},
TablineFill = {link = "VertSplit"},
VibrantBlueBackground = {bg = "#14A5FF"},
VibrantBlueBlock = {fg = "#14A5FF", bg = "#14A5FF"},
VibrantBlueText = {fg = "#14A5FF"},
VibrantGreenBackground = {bg = "#70D43A"},
VibrantGreenBlock = {fg = "#70D43A", bg = "#70D43A"},
VibrantGreenText = {fg = "#70D43A"},
NvimTreeExecFile = {link = "VibrantGreenText"},
VibrantPinkBackground = {bg = "#F500D0"},
VibrantPinkBlock = {fg = "#F500D0", bg = "#F500D0"},
VibrantPinkText = {fg = "#F500D0"},
VibrantRedBackground = {bg = "#FF1414"},
VibrantRedBlock = {fg = "#FF1414", bg = "#FF1414"},
VibrantRedText = {fg = "#FF1414"},
VibrantTurquoiseBackground = {bg = "#00F57E"},
VibrantTurquoiseBlock = {fg = "#00F57E", bg = "#00F57E"},
VibrantTurquoiseText = {fg = "#00F57E"},
NvimTreeSymlink = {link = "VibrantTurquoiseText"},
VibrantYellowBackground = {bg = "#FFB914"},
VibrantYellowBlock = {fg = "#FFB914", bg = "#FFB914"},
VibrantYellowText = {fg = "#FFB914"},
Visual = {fg = "#000000", bg = "#CCEBFF"},
VisualNOS = {},
WarningMsg = {},
WhichKey = {fg = "#A30000", bold = true},
WhichKeyDesc = {fg = "#0065A3", bold = true},
WhichKeyGroup = {fg = "#0065A3"},
WhichKeySeperator = {fg = "#B3B3B3"},
Whitespace = {fg = "#CCEBFF"},
Ignore = {link = "Whitespace"},
NonText = {link = "Whitespace"},
NvimTreeIndentMarker = {link = "Whitespace"},
fugitiveStagedModifier = {fg = "#42861D"},
fugitiveUnstagedModifier = {fg = "#CC8F00"},
fugitiveUntrackedModifier = {fg = "#A30000"},
lCursor = {},
["@constructor"] = {italic = true},
["@markup.raw"] = {bg = "#E6E6E6"},
["@puncuation.bracket"] = {fg = "#B3B3B3"},
-- PATCH_CLOSE
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='mono_lush'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
