#!/bin/bash

cp -r ~/.bashrc                ~/gits/dotfiles/.bashrc
cp -r ~/.bash_aliases          ~/gits/dotfiles/.bash_aliases
cp -r ~/.vimrc                 ~/gits/dotfiles/.vimrc
cp -r ~/.Xresources            ~/gits/dotfiles/.Xresources
cp -r ~/.config/i3/config      ~/gits/dotfiles/configi3
cp -r ~/.config/rofi/config    ~/gits/dotfiles/configrofi
cp -r ~/.templates/*           ~/gits/dotfiles/.templates/
cp -r ~/.inputrc               ~/gits/dotfiles/.inputrc
cp -r ~/.scripts/*             ~/gits/dotfiles/.scripts/
cp -r /home/ztf/.mozilla/firefox/kuikvue4.default/chrome/userChrome.css ~/gits/dotfiles/

