#!/bin/bash

date_result=$(date '+%Y-%m-%d')
filename_base=notes
filename_md=$filename_base.md
if [[ $1 =~ .*d.* ]]; then 
    filename_html="$filename_base"_dark.html
else 
    filename_html=$filename_base.html
fi

if [[ $1 =~ .*f.* ]]; then 
    echo "---" > $filename_md
    echo "title: 'Notes on ...'" >> $filename_md
    echo "---" >> $filename_md
fi

echo "" >> $filename_md
echo "***" >> $filename_md
echo "" >> $filename_md
echo "# $date_result" >> $filename_md
echo "" >> $filename_md

pandocify $filename_md
chromium-browser --app=file:`pwd`/$filename_html 2> /dev/null & 
