#!/bin/bash

filename_md=$(date '+%Y-%m-%d').md
filename_html=$(date '+%Y-%m-%d').html
echo "---" > $filename_md
echo -n "title: " >> $filename_md
date '+%Y-%m-%d' >> $filename_md
echo "---" >> $filename_md
pandocify $filename_md
chromium-browser --app=file:`pwd`/$filename_html
