#!/bin/bash 

filepath="${1%.md}"

pandoc $filepath.md \
       -s \
       -o $filepath.html \
       --mathjax \
       --highlight monochrome \
       -c ~/.pandocfiles/style.css

# DARK: 
 pandoc $filepath.md \
        -s \
        -o "$filepath"_dark.html \
        --mathjax \
        --highlight monochrome \
        -c ~/.pandocfiles/style_dark.css
